### ISSUE TITLE
testground/infra/layer2: migrating mandatory components to TF

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#150]
In part of this issue, we need to finalise what DS/STS/RS suit best for points below: 

1. Redis
2. Multus
3. Weave
4. Flannel
5. Testground-Sidecar
6. Testground-Daemon(TODO: Improvements EPIC for `cluster:k8s`)
7. Sync-Service

In addition, we need to test out the new setup with existing big network tests to close this issue

**Comment by smuu** [comment]
done
