### ISSUE TITLE
testground/daemon: improvements for `cluster:k8s`

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#151]
This issues contains 2 sub-issues for `cluster:k8s` runner in testground's daemon

- [x] #152 
- [x] #153 
- [x] #194

**Comment by smuu** [comment]
https://www.notion.so/celestiaorg/DevOps-Berlin-May-June-mini-onsite-da1c4795d16d4bedba741b93e6e41d0c#bf200c5ae55a43a2aba9f954c7b8eb24
