### ISSUE TITLE
testground/daemon/logs: remove collect-output functionality

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#152]
ATM, collector of outputs kicks in either in case of error of the pod. Or in case of successful finish of pods in the pool. 
This is not scalable as the buffer might be reached way above the limit causing the logs to be shown at all for the dev to analyse the run from pods' pov 

We need to remove this in replacement for native promtail solution that collects all outputs from pods and aggregates into a ui friendly dashboard for further analysis

**Comment by smuu** [comment]
https://www.notion.so/celestiaorg/DevOps-Berlin-May-June-mini-onsite-da1c4795d16d4bedba741b93e6e41d0c#bf200c5ae55a43a2aba9f954c7b8eb24
