### ISSUE TITLE
testground/daemon: cluster-autoscaler improvements

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#153]
ATM, the daemon is starting up the pods and throwing errors during scaling up of the cluster's instances to accommodate the load given to it. 

This can result in unstable behaviours like: 

- Some of the test pods might be evicted from run causing the whole test run to hang
- Sync-service throwing context deadline error that cause the network to be never being properly initialised

In order to fix both issues above, it might be beneficial for the daemon to know upfront when the scaling has been complete to start spinning up pods for test run

**Comment by smuu** [comment]
https://www.notion.so/celestiaorg/DevOps-Berlin-May-June-mini-onsite-da1c4795d16d4bedba741b93e6e41d0c#bf200c5ae55a43a2aba9f954c7b8eb24
