### ISSUE TITLE
docker: Images Security

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/test-infra#160]
Hello team,

The following ticket is created in order to apply the security best practices to our Docker images.

--- 

What is Docker security?

Docker security refers to the build, runtime, and orchestration aspects of Docker containers. It includes the Dockerfile security aspects of Docker base images, as well as the Docker container security runtime aspects—such as user privileges, Docker daemon, proper CPU controls for a container, and further concerns around the orchestration of Docker containers at scale.

--- 

Some interesting articles:
[Dockerfile Best Practices](https://github.com/jrmanes/dockerfile-best-practices)
[Snyk](https://snyk.io/blog/10-docker-image-security-best-practices/)

--- 

- [ ] Rootless
- [ ] Change the default UID/GID
- [ ] Verify permissions in the `/opt/celestia` -> this path is used by the service, so it has to be able to `wrx`
- [ ] Test it & verify that the service works

--- 

Next steps:
- [ ] Scan our images during the pipeline
- [ ] Create the ArgoCD app

--- 

##  This has to be done for the two services.
- [ ] [celestia-node](https://github.com/celestiaorg/celestia-node) (https://github.com/celestiaorg/celestia-node/pull/1913 & https://github.com/celestiaorg/celestia-stack-internal/pull/10)
- [ ] [celestia-app](https://github.com/celestiaorg/celestia-app) (https://github.com/celestiaorg/celestia-app/pull/1473 & https://github.com/celestiaorg/celestia-stack-internal/pull/9)
- [ ] [local-celestia-devnet](https://github.com/celestiaorg/local-celestia-devnet)
- [ ] [celestia-stack-internal](https://github.com/celestiaorg/celestia-stack-internal) See https://github.com/celestiaorg/celestia-stack-internal/pull/9 & https://github.com/celestiaorg/celestia-stack-internal/pull/10

--- 

Best 🚀 

Jose Ramon Mañes

**Comment by smuu** [comment]
- use non root user with id 1000
- golang version 1.18 not supported anymore
- Dependabot does not scan Dockerfiles in `docker` folder
