### ISSUE TITLE
testground/daemon: pod annotation and lifecycle

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#194]
Editing testground daemon for pods' annotations extremely dumb moving forward as a bullet-proof solution:

I want us to divide daemon into 2 stages:

1. Annotation of pods are handled separately from scheduling pods

- [ ] this is especially important if we want testground to be modular :smile:
- [ ] move this functionality into pod definition api of something similar to composition style 

2. Lifecycle of pods should be handled in a separate API

- [ ] each pod’s log file is like 20-30mb in debug mode and this is not maintainable to watch them in real time
- [ ] hence it will be awesome to just download + store all vanilla log files in EFS after the pod finishes main test run

Ref: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by smuu** [comment]
https://www.notion.so/celestiaorg/DevOps-Berlin-May-June-mini-onsite-da1c4795d16d4bedba741b93e6e41d0c#bf200c5ae55a43a2aba9f954c7b8eb24
