### ISSUE TITLE
testground/doc: add explanation how to run test-plan in readme file

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#37]
We need documentation that will explain to the user how to run our test-plans and where to find documentation to learn more about testground as well as how to setup infrastructure

**Comment by liamsi** [comment]
TBH, I think #27 should contain very minimal usage instructions already. Just copy the 4 lines to start the plan into the readme. You can add more complete instructions in a followup PR.

**Comment by Bidon15** [comment]
> TBH, I think #27 should contain very minimal usage instructions already. Just copy the 4 lines to start the plan into the readme. You can add more complete instructions in a followup PR.

Yeah. Definitely, I'll add some small info on running the local ones

Still, we have to add a lot more info for the infra, etc.
